name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies and build frontend
        run: |
          cd front-end
          npm install
          npm run build

      - name: Install dependencies and run backend
        run: |
          cd ../telran_project_backend-master
          npm install
          npm run dev
